apiVersion: v1
kind: ConfigMap
metadata:
  name: docker-cli
data:
  config.json: |
    {
      "apiVersion": "auto",
      "kind": "Config",
      "clusters": [
        {
          "name": "docker-cluster",
          "cluster": {
            "certificate-authority-data": "<BASE64_ENCODED_CA_CERT>",
            "server": "https://<DOCKER_HOST_IP>:<DOCKER_HOST_PORT>"
          }
        }
      ],
      "contexts": [
        {
          "name": "docker-context",
          "context": {
            "cluster": "docker-cluster",
            "user": "docker-user"
          }
        }
      ],
      "users": [
        {
          "name": "docker-user",
          "user": {
            "client-certificate-data": "<BASE64_ENCODED_CLIENT_CERT>",
            "client-key-data": "<BASE64_ENCODED_CLIENT_KEY>"
          }
        }
      ],
      "current-context": "docker-context"
    }
